---
title: "p8105_hw1_nf2429"
author: "Nathalie Fadel"
date: "9/19/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

#Problem 1
```{r}
set.seed(1)
Problem1_df = tibble(
  x = runif(10, 0, 5),
  vec_logical = (x > 2),
  vec_char = c("Carbon", "Hydrogen", "Nitrogen", "Helium", "Phosphorus", "Iodine", "Cesium", "Aluminum", "Oxygen", "Radium"),
  vec_factor = factor(c("Nonmetal", "Nonmetal", "Nonmetal", "Noble Gas", "Nonmetal", "Halogen", "Alkali Metal", "Post-transition metal", "Nonmetal", "Alkaline Earth Metal"))
) 
mean(Problem1_df$x) #this works
mean(Problem1_df$vec_logical) #this also works
mean(Problem1_df$vec_char) #this doesn't work - got 'NA' output because it's a character variable, not a numeric one
mean(Problem1_df$vec_factor) #same thing here

as.numeric(Problem1_df$vec_logical) #spits out 1s and 0s for true and false
as.numeric(Problem1_df$vec_char) #10 "NA"s
as.numeric(Problem1_df$vec_factor) #assigned categories 1-6 to each label in alphabetical order

as.factor(Problem1_df$vec_char)
as.numeric(as.factor(Problem1_df$vec_char))
as.character(Problem1_df$vec_factor)
as.numeric(as.character(Problem1_df$vec_factor)) #output gives NAs because it's a character vector
```

#Problem 2
```{r}
set.seed(1)
Problem2_df = tibble(
  x = rnorm(1000),
  y = rnorm(1000),
  z = (x + y > 0),
z_num = as.numeric(z), #outputs 1s and 0s as True and False
z_fac = as.factor(z) #outputs the True and False as characters
)
```

The dataframe contains `r nrow(Problem2_df)` observations. The mean of x is `r mean(Problem2_df$x)`. The median of x is `r median(Problem2_df$x)`. The proportion of TRUE cases is `r mean(Problem2_df$z)`. 

```{r}
problem2_plot1 <- ggplot(Problem2_df, aes(x=x, y=y, colour=z)) + geom_point() #pink and teal dots
ggsave("problem2_plot1.pdf", plot = problem2_plot1, height = 4, width = 6) 
problem2_plot1

ggplot(Problem2_df, aes(x=x, y=y, colour=z_num)) + geom_point() #blue color scale
ggplot(Problem2_df, aes(x=x, y=y, colour=z_fac)) + geom_point() #same as first plot
```


